@startuml diagramaClasesIncentivosServices

interface IncentivosServiceInterface {
    + obtenerMetricas(): Donante
    + obtenerMisiones(): List<Mision>
    + obtenerInsignias(): List<InsigniaObtenida>
    + obtenerRankingMensualActual(): RankingMensual
    + obtenerPosicionRankingActual(): int
    + procesarDonacion(): void
    + procesarDonacionExitosa(): void
}

class IncentivosService implements IncentivosServiceInterface {
    
repositorio: IncentivosRepositorioEnMemoria
notificacionClient: NotificacionClient
n8nWebhookClient: N8nWebhookClient

    + obtenerMetricas(): Donante
    + obtenerMisiones(): List<Mision>
    + obtenerInsignias(): List<InsigniaObtenida>
    + obtenerRankingMensualActual(): RankingMensual
    + obtenerPosicionRankingActual(): int
    + procesarDonacion(): void
    + procesarDonacionExitosa(): void
}

interface DonanteServiceInterface {
    + procesarAvance(): void
    + completarMision(): void
    + subirDeCategoria(): void
    + cambiarVisibilidadInsignia(): void
    + obtenerProgresoMisionActual(): int
    + obtenerDistanciaRestanteMisionActual(): int
}

class DonanteService implements DonanteServiceInterface {
    
repositoryInterface: DonanteRepositoryInterface
incentivosRepositorio: IncentivosRepositorioEnMemoria

    + procesarAvance(): void
    + completarMision(): void
    + subirDeCategoria(): void
    + cambiarVisibilidadInsignia(): void
    + obtenerProgresoMisionActual(): int
    + obtenerDistanciaRestanteMisionActual(): int
}

IncentivosService --> IncentivosRepositorioEnMemoria
IncentivosService --> NotificacionClient
IncentivosService --> N8nWebhookClient

DonanteService --> DonanteRepositoryInterface
DonanteService --> IncentivosRepositorioEnMemoria

@enduml