@startuml diagramaClasesIncentivosModel

class Donante {
    - categoria: CategoriaDonante
    - insigniasObtenidas: List<InsigniaObtenida>
    - metricas: MetricasDonante
    - progresoMision: ProgresoMision
    - ranking: RankingMensual

    + addInsignia(insignia: InsigniaObtenida): void
    + asignarMisionActual(mision: Mision): void
    + perdioRachaPorMesCompletoSinDonar(): boolean
    + subirCategoria(): boolean
}


class MetricasDonante {
    - donaciones: List<EvolucionPeriodo>
    + registrarDonacion(cantidadBienes: int, categoriasDonadas: List<String>): void
    + registrarDonacionExitosa(): void
    + totalDonacionesHistoricas(): int
    + donacionesMesActual(): int
    + donacionesExitosas(): int
    + recordBienesUnicaDonacion(): int
    + categoriasDistintasDonadas(): int
    + mesesConsecutivosDonando(fechaReferencia: LocalDate): int
    + pasoUnMesCompletoSinDonaciones(fechaReferencia: LocalDate): boolean
}

class EvolucionPeriodo {
    - fecha: LocalDate
    - cantidadBienes: int
    - categoriasDonadas: List<String>
    - exitosa: boolean
}

class ProgresoMision {
    - misionActual: Mision

    + completadaPor(donante: Donante): boolean
    + progresoActual(donante: Donante): int
    + distanciaRestante(donante: Donante): int
}

abstract class CategoriaDonante {
    + siguienteCategoria(): CategoriaDonante
}

class Colaborador extends CategoriaDonante
class Sostenedor extends CategoriaDonante
class Transformador extends CategoriaDonante

abstract class Mision {
    - nombre: String
    - descripcion: String
    - categoriaRequerida: CategoriaDonante
    - objetivo: int
    - insignia: Insignia

    + progresoActual(donante: Donante): int
    + restante(donante: Donante): int
    + estaCompletada(donante: Donante): boolean
    + otorgarInsignia(): InsigniaObtenida
}

class DonacionesExitosas extends Mision
class Racha extends Mision
class HabilDonador extends Mision
class Completitud extends Mision

class Insignia {
    - nombre: String
    - imagen: String
}

class InsigniaObtenida {
    - insignia: Insignia
    - visibilidad: boolean
    - fechaObtencion: LocalDate
}

class PosicionRanking {
    - puesto: int
    - misionesCompletadas: int
    - donacionesMesActual: int
    - totalDonacionesHistoricas: int
    - primerDiaDelMes: LocalDateTime
}

class RankingMensual {
    - mes: int
    - anio: int
    - fechaCalculo: LocalDate
    - posiciones: List<PosicionRanking>

    + top3(): List<PosicionRanking>
    + posicionDe(): int
}

Donante --> CategoriaDonante
Donante --> InsigniaObtenida
Donante --> MetricasDonante
Donante --> ProgresoMision
Donante --> RankingMensual

MetricasDonante --> EvolucionPeriodo
ProgresoMision --> Mision

Mision --> CategoriaDonante
Mision --> Insignia
InsigniaObtenida --> Insignia

RankingMensual --> PosicionRanking

@endumlgit