@startuml diagrama-De-Clases

class Categoria{
  - subcategorias: List<Subcategoria>
}

class Subcategoria{
  - idCategoria: Int
  - tipo : String
}

abstract class MedioDeContacto{

}

class Email{

}

class Telefono{

}

class Whatsapp{
}

class Bien{
    - subcategoria: Subcategoria;
    - descripcion: String;
    - foto: String;
    - cantidad: Int;
    - unidad: String; 
}

class BienConEstado{
    - esNuevo: Boolean;
}

class BienPerecible{
    - fechaVencimiento: LocalDate;
}

class Donacion{
    - estado: EstadoDonacion;
    - bien:  Bien;
    - cantidad: Int;
    - fechaIngreso: LocalDate;
    - idDonante: Int;
}

enum EstadoDonacion{
    PENDIENTE_ASIGNACION
    ASIGNADA
    EN_ENTREGA
    ENTREGADA
    VENCIDA
}

enum EstadoDonante{
    ACTIVO
    INACTIVO
}

enum Genero{
    MASCULINO
    FEMENINO
    NO_BINARIO
    OTRO
    PREFIERO_NO_DECIR
}

abstract class PersonaDonante{
    - idDonante: int;
    - tipoDocumento: String;
    - numeroDocumento: String;
    - direccion: Direccion;
    - estado: EstadoDonante;
    - donaciones: List<Donacion>;
}

class PersonaHumanaDonante{
    - nombre: String;
    - apellido: String;
    - dni: Int;
    - edad: Int;
    - genero: Genero;
    - contactos: List<MedioDeContacto>;
}

class PersonaJuridicaDonante{
    - razonSocial: String;
    - tipo : TipoPersonaJuridica;
    - rubro: String;
    - representantes : List<Representante>; 
}

class Representante{
    - nombre: String;
    - apellido: String;
    - contactos: List<MedioDeContacto>
}

enum TipoPersonaJuridica {
    GUBERNAMENTAL,
    ONG,
    EMPRESA,
    INSTITUCION
}

class Direccion{
    - calle: String;
    - numero: Int;
    - localidad: Localidad;
    - codigoPostal: String;
}

class Localidad{
- nombre: String;
- provincia: Provincia;
}

class Provincia{
- nombre: String;
}

class EntidadBeneficiaria{
    - razonSocial: String;
    - direccion: Direccion;
    - contactos: List<MedioDeContacto>;
    - representantes: List<Representante>;
    - campanias: List<Campania>;

    + registrarNecesidad(Necesidad necesidad): void;
}

abstract class Necesidad{
    - bien: Bien ;
    - descripcion: String;
    - cantidadObjetivo: Int;
    - cantidadRecibida: Int;

    + recibirDonacion(int cantidad): void;
    + estaSatisfecha(): Boolean;
}

class NecesidadExtraordinaria{

}

class NecesidadRecurrente{
    - periodo: Periodicidad;
    - fechaInicioPeriodo;

    + reiniciarPeriodo(): void;
    + requiereReinicio(LocalDate fechaActual): Boolean;
}

enum Periodicidad{
    SEMANAL,
    MENSUAL,
    CUATRIMESTRAL,
    ANUAL
}

class Campania{
    - necesidades: List<Necesidad>;
    - fechaInicio: LocalDate;
}

Campania --* Necesidad


Bien <|-- BienConEstado
Bien <|-- BienPerecible


Donacion --* Bien
Donacion -- EstadoDonacion



PersonaDonante <|-- PersonaHumanaDonante
PersonaDonante <|-- PersonaJuridicaDonante
PersonaDonante --* Donacion
PersonaHumanaDonante --* MedioDeContacto
PersonaDonante --* Direccion
PersonaDonante -- EstadoDonante

MedioDeContacto <|-- Email
MedioDeContacto <|-- Telefono
MedioDeContacto <|-- Whatsapp

Representante --* MedioDeContacto

Necesidad <|-- NecesidadExtraordinaria
Necesidad <|-- NecesidadRecurrente
Necesidad --* Bien


NecesidadRecurrente -- Periodicidad

PersonaJuridicaDonante -- TipoPersonaJuridica
PersonaJuridicaDonante --* Representante

PersonaHumanaDonante -- Genero

EntidadBeneficiaria --* Campania
EntidadBeneficiaria --* Direccion
EntidadBeneficiaria --* Representante
EntidadBeneficiaria --* MedioDeContacto

Direccion --* Localidad
Localidad --* Provincia

Categoria --* Subcategoria
Subcategoria *-- Bien

@enduml