@startuml diagrama-De-Clases

class Categoria{
  - subcategorias: List<Subcategoria>
}

class Subcategoria{
  - idCategoria: Int
  - tipo : String
}

class TipoMedioContacto{

}

class Email{

}

class Telefono{

}

class Whatsapp{

}

class Bien{
    - subcategoria: Subcategoria;
    - descripcion: String;
    - foto: String; 
    - unidad: String; 
}

class BienConEstado{
    - esNuevo: Boolean;
}

class BienPerecible{
    - fechaVencimiento: LocalDate;
}

class CargaDonacion{
    - descripcionGeneral: String;
    - fechaIngreso: LocalDate;
    - donaciones:  List<Donacion>;
}

class Donacion{
    - estado: EstadoDonacion;
    - bien:  Bien;
    - cantidad: Int;
}

class DonacionConEstado{
    - esNuevo: Boolean;
}

class DonacionPerecible{
    - fechaVencimiento: LocalDate;
}

enum EstadoDonacion{
    PENDIENTE_ASIGNACION
    ASIGNADA
    EN_ENTREGA
    ENTREGADA
    VENCIDA
}

enum EstadoDonante{
    ACTIVO
    INACTIVO
}

enum Genero{
    MASCULINO
    FEMENINO
    NO_BINARIO
    OTRO
    PREFIERO_NO_DECIR
}

class PersonaDonante{
    - tipoDocumento : String; 
    - numeroDocumento : String;
    - direccion : Direccion;
    - email: String;
    - telefono: String;
    - medioContactoPredeterminado: TipoMedioContacto;
    - estado: EstadoDonante;
    - donaciones: List<CargaDonacion>;
}

class PersonaHumanaDonante{
    - nombre: String;
    - apellido: String;
    - edad: Int;
    - genero: Genero;
}

class PersonaJuridicaDonante{
    - razonSocial: String;
    - tipo : TipoPersonaJuridica;
    - rubro: String;
    - representantes : List<Representante>; 
}

class Representante{
    - nombre: String;
    - apellido: String;
    - email: String;
    - telefono: String;
}

enum TipoPersonaJuridica {
    GUBERNAMENTAL,
    ONG,
    EMPRESA,
    INSTITUCION
}

class Direccion{
    - calle: String;
    - numero: Int;
    - localidad: Localidad;
    - provincia: Provincia;
    - codigoPostal: String;
}

class Localidad{
- nombre: String;
- provincia : Provincia
}

class Provincia{
- nombre: String;
}

class EntidadBeneficiaria{
    - razonSocial: String;
    - direccion: Direccion;
    - telefono: String;
    - correosRepresentatnes: List<String>;
    - necesidades: List<CargaNecesidad>;

    + registrarNecesidad(Necesidad necesidad): void;
}

class Necesidad{
    - subcategoria: Subcategoria;
    - descripcion: String;
    - cantidadObjetivo: Int;
    - cantidadRecibida: Int;

    + recibirDonacion(int cantidad): void;
    + estaSatisfecha(): Boolean;
}

class CargaNecesidad{
    - necesidades:  List<Necesidad>;
    - fechaIngreso: LocalDate;
}

class NecesidadExtraordinaria{

}

class NecesidadRecurrente{
    - periodo: Periodicidad;
    - fechaInicioPeriodo;

    + reiniciarPeriodo(): void;
    + requiereReinicio(LocalDate fechaActual): Boolean;
}

enum Periodicidad{
    SEMANAL,
    MENSUAL,
    CUATRIMESTRAL,
    ANUAL
}

Bien <|-- BienConEstado
Bien <|-- BienPerecible

Donacion <|-- DonacionConEstado
Donacion <|-- DonacionPerecible
Donacion -- Bien
Donacion -- EstadoDonacion

CargaDonacion --* Donacion

PersonaDonante <|-- PersonaHumanaDonante
PersonaDonante <|-- PersonaJuridicaDonante
PersonaDonante -- TipoMedioContacto
PersonaDonante --* CargaDonacion
PersonaDonante --* Direccion
PersonaDonante -- EstadoDonante

TipoMedioContacto <|-- Email
TipoMedioContacto <|-- Telefono
TipoMedioContacto <|-- Whatsapp

Necesidad <|-- NecesidadExtraordinaria
Necesidad <|-- NecesidadRecurrente
Necesidad -- Subcategoria

CargaNecesidad --* Necesidad

NecesidadRecurrente -- Periodicidad

PersonaJuridicaDonante -- TipoPersonaJuridica
PersonaJuridicaDonante --* Representante

PersonaHumanaDonante -- Genero

EntidadBeneficiaria --* CargaNecesidad
EntidadBeneficiaria --* Direccion

Direccion -- Localidad
Localidad -- Provincia

Categoria --* Subcategoria
Subcategoria *-- Bien

@enduml